export const ADD_TODO = 'ADD_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const REMOVE_ALL_TODO = 'REMOVE_ALL_TODO';
export const LOAD_FROM_LOCAL = 'LOAD_FROM_LOCAL';
export const ADD_HASHTAG_ITEM = 'ADD_HASHTAG_ITEM';
export const CHANGE_HASHTAG_ITEM = 'CHANGE_HASHTAG_ITEM'
export const UPDATE_HASHTAG_VALUE = 'UPDATE_HASHTAG_VALUE'